# .github/workflows/second-workflow.yml
name: Second Workflow

on:
  workflow_run:
    workflows: ["FirstFlow"]  # Name of the first workflow
    types:
      - completed  # Trigger when the first workflow is completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for 30 seconds
        run: sleep 30  # Delay for 60 seconds (1 minute)

      - name: Call External API
        run: |
          curl -X POST https://aeg55b5wgb.execute-api.us-west-2.amazonaws.com/pord/path \
          -H "Content-Type: application/json" \
          -d '{}'
